book_catalog/apps/books/urls.py
from django.urls import path

from .views import BookDetailView, BookListView, BooksByCategoryListView, IndexTemplateView

urlpatterns = [
    path("", IndexTemplateView.as_view(), name="index"),
    path("categories/<int:id>/books/", BooksByCategoryListView.as_view(), name="book-by-category-list"),
    path("books/", BookListView.as_view(), name="books-list"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="books-detail"),
]

book_catalog/apps/users/urls.py
from django.urls import path

from book_catalog.apps.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include(("book_catalog.apps.books.urls", "book_catalog.apps.books"), namespace="books",)),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("book_catalog.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

book_catalog/apps/authors/models.py
from django.db import models


class Author(models.Model):
    """
    Model for Author
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """
        String for representing the Model object.
        """
        return f"{self.first_name}   {self.last_name}"

book_catalog/apps/books/models.py
from django.db import models

from book_catalog.apps.authors.models import Author
from book_catalog.apps.books.utils import get_cover_image_upload_path, valid_jpeg_or_png


class Category(models.Model):
    """
    Model for Category
    """
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, help_text="Summary of the book")

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class Book(models.Model):
    """
    Model for Book
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Summary of the book")
    categories = models.ManyToManyField(Category, help_text="Category of the book")
    cover_image = models.ImageField(
        null=True,
        blank=True,
        upload_to=get_cover_image_upload_path,
        help_text="Book cover image in png/jpg file",
        validators=[valid_jpeg_or_png]
    )

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def cover_image_url(self):
        """
        Get book cover image url
        """
        if not self.cover_image:
            return "https://i.imgur.com/NAZWTGP.png"

        return self.cover_image.url

    def display_categories(self):
        """
        Display list of categories in Admin
        """
        return ', '.join([genre.name for genre in self.categories.all()])

    display_categories.short_description = 'Categories'

book_catalog/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from book_catalog.apps.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Book Catalog.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

book_catalog/apps/users/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

book_catalog/apps/authors/views.py
from django.shortcuts import render

# Create your views here.

book_catalog/apps/books/views.py
from typing import Any

from django.views.generic import DetailView, ListView, TemplateView

from book_catalog.apps.books.models import Book, Category


class IndexTemplateView(TemplateView):
    """
    Index template view for home page
    """
    template_name = "base.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context.update({
            'categories': categories
        })
        return context


class BooksByCategoryListView(TemplateView):
    """
    Template view for Books by category
    """
    template_name = "books/books_by_category.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(id=kwargs.get('id'))
        books = category.book_set.all()
        context.update({
            "books": books,
            "category": category,
        })
        return context


class BookListView(ListView):
    """
    List of books and search books view
    """
    model = Book
    template_name = "books/book_list.html"
    context_object_name = "all_search_results"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        last_query = self.request.GET.get('query', "")
        context.update({
            "last_query": last_query,
        })
        return context

    def get_queryset(self):
       queryset = super().get_queryset()
       query = self.request.GET.get('query')

       if query:
          postresult = Book.objects.filter(title__icontains=query)
          queryset = postresult

       return queryset


class BookDetailView(DetailView):
    """
    Detail view for Book
    """
    model = Book

book_catalog/apps/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

book_catalog/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

book_catalog/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <title>
        {% block title %}
            Book Catalog
        {% endblock title %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description"
          content="Simple Book Catalog Website that allows users to browse and explore a collection of books."/>
    <meta name="author"
          content="Nikko Comidoy"/>
    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}"/>
    {% block css %}
        <!-- Latest compiled and minified Bootstrap CSS -->
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
              integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
              crossorigin="anonymous"
              referrerpolicy="no-referrer"/>
        <!-- Your stuff: Third-party CSS libraries go here -->
        <!-- This file stores project-specific CSS -->


        <link href="{% static 'css/project.css' %}" rel="stylesheet"/>


    {% endblock css %}
    <!-- Le javascript
        ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}


        <!-- Bootstrap JS -->
        <script defer
                src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
                integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
                crossorigin="anonymous"
                referrerpolicy="no-referrer"></script>
        <!-- Your stuff: Third-party javascript libraries go here -->


        <!-- place project specific Javascript in this file -->


        <script defer src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
</head>
<body>
<div class="mb-1">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler navbar-toggler-right"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url 'books:index' %}">Book Catalog</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'books:books-list' %}">All books</a>
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link"
                               href="{% url 'users:detail' request.user.pk %}">{% translate "My Profile" %}</a>
                        </li>
                        <li class="nav-item">
                            {# URL provided by django-allauth/account/urls.py #}
                            <a class="nav-link" href="{% url 'account_logout' %}">{% translate "Sign Out" %}</a>
                        </li>
                    {% else %}
                        {% if ACCOUNT_ALLOW_REGISTRATION %}
                            <li class="nav-item">
                                {# URL provided by django-allauth/account/urls.py #}
                                <a id="sign-up-link" class="nav-link"
                                   href="{% url 'account_signup' %}">{% translate "Sign Up" %}</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            {# URL provided by django-allauth/account/urls.py #}
                            <a id="log-in-link" class="nav-link"
                               href="{% url 'account_login' %}">{% translate "Sign In" %}</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
                <button type="button"
                        class="btn-close"
                        data-bs-dismiss="alert"
                        aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
        <div class="container text-center">
            <div class="row row-cols-3">
                {% for category in categories %}
                    <div class="col">
                        <div class="card" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title">{{ category.name }}</h5>
                                <p class="card-text">{{ category.description }}</p>
                                <a href="{% url 'books:book-by-category-list' category.id %}" class="btn btn-primary">See
                                    list of books</a>
                            </div>
                        </div>
                    </div>
                    {% empty %}
                        No categories yet.
                {% endfor %}
            </div>
        </div>
    {% endblock content %}
</div>
<!-- /container -->
{% block modal %}
{% endblock modal %}
{% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %}
{% endblock inline_javascript %}
</body>
</html>