book_catalog/apps/books/urls.py
from django.urls import path

from .views import BookDetailView, BookListView, BooksByCategoryListView, IndexTemplateView

urlpatterns = [
    path("", IndexTemplateView.as_view(), name="index"),
    path("categories/<int:id>/books/", BooksByCategoryListView.as_view(), name="book-by-category-list"),
    path("books/", BookListView.as_view(), name="books-list"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="books-detail"),
]

book_catalog/apps/users/urls.py
from django.urls import path

from book_catalog.apps.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", include(("book_catalog.apps.books.urls", "book_catalog.apps.books"), namespace="books",)),
    path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("book_catalog.apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

book_catalog/apps/authors/models.py
from django.db import models


class Author(models.Model):
    """
    Model for Author
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        """
        String for representing the Model object.
        """
        return f"{self.first_name}   {self.last_name}"

book_catalog/apps/books/models.py
from django.db import models

from book_catalog.apps.authors.models import Author
from book_catalog.apps.books.utils import get_cover_image_upload_path, valid_jpeg_or_png


class Category(models.Model):
    """
    Model for Category
    """
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000, help_text="Summary of the book")

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name


class Book(models.Model):
    """
    Model for Book
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text="Summary of the book")
    categories = models.ManyToManyField(Category, help_text="Category of the book")
    cover_image = models.ImageField(
        null=True,
        blank=True,
        upload_to=get_cover_image_upload_path,
        help_text="Book cover image in png/jpg file",
        validators=[valid_jpeg_or_png]
    )

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def cover_image_url(self):
        """
        Get book cover image url
        """
        if not self.cover_image:
            return "https://i.imgur.com/NAZWTGP.png"

        return self.cover_image.url

    def display_categories(self):
        """
        Display list of categories in Admin
        """
        return ', '.join([genre.name for genre in self.categories.all()])

    display_categories.short_description = 'Categories'

book_catalog/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from book_catalog.apps.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Book Catalog.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

book_catalog/apps/users/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """

book_catalog/apps/authors/views.py
from django.shortcuts import render

# Create your views here.

book_catalog/apps/books/views.py
from typing import Any

from django.views.generic import DetailView, ListView, TemplateView

from book_catalog.apps.books.models import Book, Category


class IndexTemplateView(TemplateView):
    """
    Index template view for home page
    """
    template_name = "base.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        categories = Category.objects.all()
        context.update({
            'categories': categories
        })
        return context


class BooksByCategoryListView(TemplateView):
    """
    Template view for Books by category
    """
    template_name = "books/books_by_category.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(id=kwargs.get('id'))
        books = category.book_set.all()
        context.update({
            "books": books,
            "category": category,
        })
        return context


class BookListView(ListView):
    """
    List of books and search books view
    """
    model = Book
    template_name = "books/book_list.html"
    context_object_name = "all_search_results"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        last_query = self.request.GET.get('query', "")
        context.update({
            "last_query": last_query,
        })
        return context

    def get_queryset(self):
       queryset = super().get_queryset()
       query = self.request.GET.get('query')

       if query:
          postresult = Book.objects.filter(title__icontains=query)
          queryset = postresult

       return queryset


class BookDetailView(DetailView):
    """
    Detail view for Book
    """
    model = Book

book_catalog/apps/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

book_catalog/templates/books/book_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row pt-5">
            <div class="col-12">
                <h3 class="text-uppercase border-bottom mb-4">{{ book.title }}</h3>
            </div>
        </div>
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <p class="card-text"><strong>Summary:</strong> {{ book.summary }}</p>
                    <p class="card-text"><strong>Categories:</strong> {{ book.display_categories }}</p>
                    <p class="card-text"><strong>Authored by:</strong> {{ book.author }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

book_catalog/templates/books/book_list.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-borderless">
        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'books:books-list' %}">
            <tr>
                <td><input class="form-control mr-sm-2" type="search" name="query" value="{{ last_query }}"></td>
                <td>
                    <button class="btn btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                </td>
            </tr>
        </form>
    </table>
    <div class="container">
        <div class="row">
            {% for book in all_search_results %}
                <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                    <div class="card">
                        <img src="{{ book.cover_image_url }}"
                             class="card-img-top"
                             alt="Card Image">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <p class="card-text mb-4">{{ book.summary }}</p>
                            <a href="{% url 'books:books-detail' book.id %}" class="btn btn-primary">Book details</a>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary">Authored by: {{ book.author }}</small>
                        </div>
                    </div>
                </div>
            {% empty %}
                <h2>No results found</h2>
            {% endfor %}
        </div>
    </div>
{% endblock content %}

book_catalog/templates/books/books_by_category.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
    <div class="container">
        <div class="row pt-5">
            <div class="col-12">
                <h3 class="text-uppercase border-bottom mb-4">{{ category.name }} category</h3>
            </div>
        </div>
        <div class="row">
            {% for book in books %}
                <div class="col-lg-4 mb-3 d-flex align-items-stretch">
                    <div class="card">
                        <img src="{{ book.cover_image_url }}"
                             class="card-img-top"
                             alt="Card Image">
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title">{{ book.title }}</h5>
                            <p class="card-text mb-4">{{ book.summary }}</p>
                            <a href="{% url 'books:books-detail' book.id %}" class="btn btn-primary">Book details</a>
                        </div>
                        <div class="card-footer">
                            <small class="text-body-secondary">Authored by: {{ book.author }}</small>
                        </div>
                    </div>
                </div>
                {% empty %}
                    No books added yet.
            {% endfor %}
        </div>
    </div>
{% endblock content %}